import Link from "next/link";
import "../globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="bg-gradient-to-r from-gray-400  to-purple-300  text-red-900 text-4xl font-extrabold text-center h-20 flex  justify-center items-center">welcome to my website</div>
        <div className="bg-gradient-to-r from-gray-400  to-purple-300  text-red-500 w-[200px] float-left h-screen">
          <ul className=" bg-gradient-to-r from-purple-300  to-gray-400   text-red-800 p-5 space-y-4">
          <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/dashboard">Dashboard</Link>
            </li>
            <li>
            <Link href="/profile">Profile</Link>
            </li> <li>
            <Link href="/contact">Contact-us</Link>
            </li>
            <li>
            <Link href="/about">About-us</Link>
            </li>
            <li>
            <Link href="../login">Logout</Link>
            </li>
          </ul>
        </div>
        <div className="bg-gradient-to-r from-blue-300  to-indigo-400 
        shadow-[0_0_10px_5px_rgba(0,0,0,0.5)_0_0_20px_10px_rgba(0,0,0,0.2)] 
        text-red-500 ml-48 h-screen flex justify-center items-center text-center">
          {children}
        </div>
        </body>
    </html>
  )
}